version: '3.5'

services:
  django:
    image: betagouv/mrs:test
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
    - django-spooler-mail:/app/spooler/mail
    - django-spooler-stat:/app/spooler/stat
    depends_on:
    - postgres
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: postgres
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      DB_PORT: 5432

  postgres:
    image: postgres:10
    restart: unless-stopped
    logging:
      driver: journald
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./backup/postgres:/backup
    labels:
      io.compoctl.backup.cmd: pg_dumpall -U ${POSTGRES_USER-postgres} -f /backup/data.dump
      io.compoctl.restore.cmd: psql -U ${POSTGRES_USER-postgres} -f /backup/data.dump

volumes:
  postgres-data:
  django-spooler-mail:
  django-spooler-stat:
